apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values "openstack-cluster").cloudCredentialsSecretName }}
  annotations:
    # If the cloud credentials are deleted before the cluster has finished deleting, then the cluster
    # deletion cannot proceed any further. So prevent Helm from deleting it.
    helm.sh/resource-policy: keep
    # For Argo, this resource should be pruned last out of everything
    argocd.argoproj.io/sync-options: PruneLast=true
stringData:
  # Just include the data for the cloud we will be using
  clouds.yaml: |
    clouds:
      openstack:
        {{ $cloudName := index .Values "openstack-cluster" "cloudName" -}}
        {{- index .Values.clouds $cloudName | toYaml | indent 8 | trim -}}
  {{- if .Files.Glob "include/cloudCA.crt" }}
  cacert: |
    {{ .Files.Get "include/cloudCA.crt" | indent 4 | trim }}
  {{- end }}