---
apiVersion: v1
kind: Secret
metadata:
  name: git-deploy-keys
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $index, $repo := .Values.gitRepos }}
  {{ $repo.name }}-key: {{ $repo.deployKey | b64enc }}
  {{- end }}