# Entrypoint scripts
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-entrypoints
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "include/kinit.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "include/sidecar-entrypoint.sh").AsConfig | indent 2 }}

# File configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kerberos-files
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "include/krb5.conf").AsConfig | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-trusted-certs
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "include/aquilon-gridpp-rl-ac-uk-chain.pem").AsConfig | indent 2 }}

# Env configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kerberos-env
  namespace: {{ .Release.Namespace }}
data:
  PERIOD_SECONDS: "{{ .Values.kerberosSidecar.refreshInterval }}"
  KRB5_PRINCIPLE: {{ .Values.kerberosSidecar.principle }}
  KRB5CCNAME: "/shared/krb5cc"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-consumer-env
  namespace: {{ .Release.Namespace }}
data:
  LOG_LEVEL: {{ .Values.consumer.logLevel }}

  AQ_ARCHETYPE: {{ .Values.consumer.aquilon.defaultArchetype }}
  AQ_DOMAIN: {{ .Values.consumer.aquilon.defaultDomain }}
  AQ_PERSONALITY: {{ .Values.consumer.aquilon.defaultPersonality }}
  AQ_PREFIX: {{ .Values.consumer.aquilon.defaultPrefix }}
  AQ_URL: {{ .Values.consumer.aquilon.url }}

  RABBIT_HOST: {{ .Values.consumer.rabbitmq.host }}
  RABBIT_PORT: "{{ .Values.consumer.rabbitmq.port }}"

  OPENSTACK_AUTH_URL: {{ .Values.consumer.openstack.authUrl }}
  OPENSTACK_COMPUTE_URL: {{ .Values.consumer.openstack.computeUrl }}
  OPENSTACK_DOMAIN_NAME: {{ .Values.consumer.openstack.domainName }}
  OPENSTACK_PROJECT_ID: {{ .Values.consumer.openstack.projectId }}