
openstack-cluster:
  # List of comma separated additional packages to install on cluster nodes
  additionalPackages: []

  controlPlane:
    # The number of control plane machines to deploy
    # For high-availability, this should be greater than 1
    # For etcd quorum, it should be odd - usually 3, or 5 for very large clusters
    machineCount: 5
    # The flavor to use for control plane machines
    machineFlavor: l3.nano

    # defaults cause OutofSync issues in argocd
    remediationStrategy:
      retryPeriod: 20m0s
      minHealthyPeriod: 1h0m0s

  addons:
    # Monitoring sets up kube-prometheus-stack and loki-stack.
    monitoring:
      enabled: false

    # Ingress is preferred, as it allows you to use DNS to locate multiple
    # services behind a single FIP, and makes TLS trivial
    # see https://stfc.atlassian.net/wiki/spaces/CLOUDKB/pages/309854262/CAPI+Ingress
    ingress:
      enabled: false
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: # "130.x.y.z"

  # Settings for node-level registry auth if using a private registry
  registryAuth:
    {}
    # registry-1.docker.io:
    #   username: "<username>"
    #   password: "<password>"

  # The name of the SSH key to inject into cluster machines, this can be
  # left blank if a user does not require SSH access to the machines
  machineSSHKeyName:
