{{- range $cloud, $cfg := .Values.clouds }}
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-manila-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  os-region: {{ $cfg.region_name | b64enc }}
  os-authURL: {{ $cfg.auth.auth_url | b64enc }}
  os-applicationCredentialID: {{ $cfg.auth.application_credential_id | b64enc }}
  os-applicationCredentialSecret: {{ $cfg.auth.application_credential_secret | b64enc }}
{{- end }}