name: lint stfc-cloud-cert-manager chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/cert_manager_chart.yaml"
      - "charts/stfc-cloud-cert-manager/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm dependency update charts/stfc-cloud-cert-manager/.
          helm lint charts/stfc-cloud-cert-manager --values charts/stfc-cloud-cert-manager/values.yaml --strict=true
