name: lint chatops Chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/chatops_chart.yaml"
      - "charts/chatops/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          cp charts/chatops/secret-values.yaml.template /tmp/secret-values.yaml
          helm dependency update charts/chatops/.
          helm lint charts/chatops --values charts/chatops/values.yaml --values /tmp/secret-values.yaml --strict=true
