name: lint longhorn chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/longhorn_chart.yaml"
      - "charts/stfc-cloud-longhorn/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm dependency update charts/stfc-cloud-longhorn/.
          helm lint charts/stfc-cloud-longhorn --values charts/stfc-cloud-longhorn/values.yaml --strict=true
