name: lint manila-csi chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/manila_csi_chart.yaml"
      - "charts/stfc-cloud-manila-csi/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Setup Dummy clouds.yaml
        run: | 
          cat << EOF > charts/stfc-cloud-manila-csi/clouds.yaml
          clouds:
            openstack:
              auth:
                auth_url: "foo.example.com"
                application_credential_id: "foo"
                application_credential_secret: "bar"
              region_name: "biz"
              interface: "public"
              identity_api_version: 3
              auth_type: "v3applicationcredential"
          EOF
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm dependency update charts/stfc-cloud-manila-csi/.
          helm lint charts/stfc-cloud-manila-csi --values charts/stfc-cloud-manila-csi/values.yaml --values charts/stfc-cloud-manila-csi/clouds.yaml --strict=true
