name: lint opensearch chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/materials_galaxy_chart.yaml"
      - "charts/materials-galaxy/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          cp charts/materials-galaxy/secret-values.yaml.template /tmp/secret-values.yaml
          helm dependency update charts/materials-galaxy/.
          helm lint charts/materials-galaxy --values charts/materials-galaxy/values.yaml --values /tmp/secret-values.yaml --strict=true
