name: lint rabbit consumer chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/rabbit_consumer_chart.yaml"
      - "charts/rabbit-consumer/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm lint charts/rabbit-consumer --values charts/rabbit-consumer/values.yaml --values charts/rabbit-consumer/dev-values.yaml --strict=true
