name: lint stfc-cloud-openstack-cluster chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/stfc_cloud_openstack_cluster_chart.yaml"
      - "charts/stfc-cloud-openstack-cluster/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint bootstrap script
        uses: azohra/shell-linter@latest
        with:
          path: "charts/stfc-cloud-openstack-cluster/script/bootstrap.sh"
      - name: Lint set-project-id script
        uses: azohra/shell-linter@latest
        with:
          path: "charts/stfc-cloud-openstack-cluster/script/set-project-id.sh"
      - name: Create fake clouds.yaml file
        run: |
          cat > clouds.yaml << 'EOF'
          clouds:
            openstack:
              auth:
                auth_url: example.com
                application_credential_id: foo
                application_credential_secret: bar
              region_name: region
              interface: interface
              identity_api_version: v3
              auth_type: app-cred
          EOF
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm dependency update charts/stfc-cloud-openstack-cluster/.
          helm lint charts/stfc-cloud-openstack-cluster \
            --values charts/stfc-cloud-openstack-cluster/values.yaml \
            --values charts/stfc-cloud-openstack-cluster/nodes.yaml \
            --values charts/stfc-cloud-openstack-cluster/addons.yaml \
            --values clouds.yaml \
            --set openstack-cluster.apiServer.floatingIP=127.0.0.1 \
            --strict=true
