name: lint stfc-cloud-openstack-cluster chart
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/stfc_cloud_openstack_cluster_chart.yaml"
      - "charts/stfc-cloud-openstack-cluster/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint bootstrap script
        uses: azohra/shell-linter@latest
        with:
          path: "charts/stfc-cloud-openstack-cluster/script/bootstrap.sh"
      - name: Lint set-project-id script
        uses: azohra/shell-linter@latest
        with:
          path: "charts/stfc-cloud-openstack-cluster/script/set-project-id.sh"
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm dependency update charts/stfc-cloud-openstack-cluster/.
          helm lint charts/stfc-cloud-openstack-cluster --values charts/stfc-cloud-openstack-cluster/values.yaml --values charts/stfc-cloud-openstack-cluster/nodes.yaml --values charts/stfc-cloud-openstack-cluster/addons.yaml --set openstack-cluster.apiServer.floatingIP=127.0.0.1 --strict=true
